version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5232:8080"  # Map container's port 80 to host's port 5232
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Map container's port 3000 to host's port 3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
